# Generated by Django 4.0.4 on 2022-04-27 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Wikipedia Article Title')),
                ('language', models.CharField(choices=[('bn', 'Bengali'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('ne', 'Nepali'), ('or', 'Oriya'), ('pa', 'Punjabi'), ('si', 'Sinhala'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ur', 'Urdu')], max_length=2, verbose_name='Target Language')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Project Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.TextField(verbose_name='Original Sentence')),
                ('translated_sentence', models.TextField(blank=True, null=True, verbose_name='Translated Sentence')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.project', verbose_name='Project')),
            ],
        ),
    ]
