# Generated by Django 4.0.4 on 2022-04-28 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_project_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time Created'),
            preserve_default=False,
        ),
    ]
