# Generated by Django 4.0.4 on 2022-04-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_project_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_projects',
            field=models.ManyToManyField(blank=True, to='translate.project'),
        ),
    ]
