name: Deploy to Heroku

on:
  push:
    branches: main

jobs:
  build:
    name: "Deploy app to Heroku"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge 'main' into 'heroku'
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: heroku
          github_token: ${{ github.token }}

      - name: Git deploy to Heroku
        uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: "wikitranslate-nishant"
          email: "nishantnayak2001@gmail.com"
          heroku_branch: "heroku"
          subfolder: ""
