name: Deploy to Heroku

on:
  push:
    branches: main

jobs:
  build:
    name: "Deploy app to Heroku"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge 'main' into 'heroku'
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: heroku
          github_token: ${{ github.token }}

      - name: Heroku Deployment
        uses: ElayGelbart/Heroku-Auto-Deployment@v1.0.6
        with:
          herokuApiKey: ${{ secrets.HEROKU_API_KEY }}
          herokuAppName: "wikitranslate-nishant"
          branch: "heroku"
